// ============================================================
// Design Tools — 9 tools
// Color Picker & Contrast, Box Shadow, CSS Gradient,
// Border Radius, Text Shadow, Circle Generator, QR Code,
// CSS Button Generator, Lorem Placeholder Images
// ============================================================
function $(id){return document.getElementById(id);}

// ─── Color Picker & Contrast Checker ───
const colorPicker={name:'Color Picker & Contrast',icon:'🎨',render:()=>`<div class="panel"><h2>Color Picker & Contrast Checker</h2><p class="desc">Pick colors and check WCAG contrast ratios.</p><div style="display:flex;gap:var(--sp-4);flex-wrap:wrap;margin-bottom:var(--sp-4)"><div><label>Foreground</label><div style="display:flex;gap:var(--sp-2);align-items:center"><input type="color" id="cc-fg" value="#ffffff" oninput="ccCheck()" /><input type="text" id="cc-fg-hex" value="#ffffff" style="width:100px" oninput="$('cc-fg').value=this.value;ccCheck()" /></div></div><div><label>Background</label><div style="display:flex;gap:var(--sp-2);align-items:center"><input type="color" id="cc-bg" value="#2563eb" oninput="ccCheck()" /><input type="text" id="cc-bg-hex" value="#2563eb" style="width:100px" oninput="$('cc-bg').value=this.value;ccCheck()" /></div></div></div><div id="cc-preview" style="padding:var(--sp-6);border-radius:var(--r-md);text-align:center;font-size:var(--text-xl);font-weight:600;margin-bottom:var(--sp-4)">Sample Text Preview</div><div class="output" id="cc-out" style="min-height:auto">Loading…</div></div>`,init:()=>{ccCheck();}};
function lum(r,g,b){const a=[r,g,b].map(v=>{v/=255;return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4);});return a[0]*0.2126+a[1]*0.7152+a[2]*0.0722;}
function cr(l1,l2){return(Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05);}
function h2r(h){h=h.replace('#','');if(h.length===3)h=h[0]+h[0]+h[1]+h[1]+h[2]+h[2];return{r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)};}
window.ccCheck=()=>{const fg=$('cc-fg').value,bg=$('cc-bg').value;$('cc-fg-hex').value=fg;$('cc-bg-hex').value=bg;$('cc-preview').style.color=fg;$('cc-preview').style.background=bg;const f=h2r(fg),b=h2r(bg);const ratio=cr(lum(f.r,f.g,f.b),lum(b.r,b.g,b.b));$('cc-out').textContent=`Contrast Ratio: ${ratio.toFixed(2)}:1\n\nWCAG AA  (Normal): ${ratio>=4.5?'✅ Pass':'❌ Fail'}  (4.5:1)\nWCAG AA  (Large):  ${ratio>=3?'✅ Pass':'❌ Fail'}  (3:1)\nWCAG AAA (Normal): ${ratio>=7?'✅ Pass':'❌ Fail'}  (7:1)\n\nFG: ${fg}  BG: ${bg}`;};

// ─── Box Shadow Generator ───
const boxShadow={name:'Box Shadow Generator',icon:'🔲',render:()=>`<div class="panel"><h2>CSS Box Shadow Generator</h2><p class="desc">Generate CSS box-shadow with live preview.</p><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:var(--sp-3);margin-bottom:var(--sp-4)"><div><label>X Offset</label><input type="range" id="bs-x" min="-50" max="50" value="0" oninput="bsUp()" /><span id="bs-xv" style="font-size:var(--text-xs);color:var(--ink-4)">0px</span></div><div><label>Y Offset</label><input type="range" id="bs-y" min="-50" max="50" value="4" oninput="bsUp()" /><span id="bs-yv" style="font-size:var(--text-xs);color:var(--ink-4)">4px</span></div><div><label>Blur</label><input type="range" id="bs-bl" min="0" max="100" value="12" oninput="bsUp()" /><span id="bs-bv" style="font-size:var(--text-xs);color:var(--ink-4)">12px</span></div><div><label>Spread</label><input type="range" id="bs-sp" min="-50" max="50" value="0" oninput="bsUp()" /><span id="bs-sv" style="font-size:var(--text-xs);color:var(--ink-4)">0px</span></div><div><label>Color</label><input type="color" id="bs-c" value="#00000033" oninput="bsUp()" /></div><div><label>Inset</label><select id="bs-ins" onchange="bsUp()"><option value="">No</option><option value="inset ">Yes</option></select></div></div><div style="display:flex;align-items:center;justify-content:center;padding:var(--sp-10);background:var(--surface-sunken);border-radius:var(--r-md);margin-bottom:var(--sp-4)"><div id="bs-box" style="width:120px;height:80px;background:var(--surface);border-radius:var(--r-md);border:1px solid var(--border)"></div></div><div class="output" id="bs-out" style="min-height:auto">Loading…</div></div>`,init:()=>{bsUp();}};
window.bsUp=()=>{const x=$('bs-x').value,y=$('bs-y').value,bl=$('bs-bl').value,sp=$('bs-sp').value,c=$('bs-c').value,ins=$('bs-ins').value;$('bs-xv').textContent=x+'px';$('bs-yv').textContent=y+'px';$('bs-bv').textContent=bl+'px';$('bs-sv').textContent=sp+'px';const css=`box-shadow: ${ins}${x}px ${y}px ${bl}px ${sp}px ${c};`;$('bs-box').style.boxShadow=`${ins}${x}px ${y}px ${bl}px ${sp}px ${c}`;$('bs-out').textContent=css;};

// ─── CSS Gradient Generator ───
const cssGradient={name:'CSS Gradient Generator',icon:'🌈',render:()=>`<div class="panel"><h2>CSS Gradient Generator</h2><p class="desc">Create linear, radial, and conic gradients.</p><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;align-items:end;margin-bottom:var(--sp-4)"><div><label>Type</label><select id="gr-type" onchange="grUp()"><option value="linear">Linear</option><option value="radial">Radial</option><option value="conic">Conic</option></select></div><div><label>Angle</label><input type="range" id="gr-ang" min="0" max="360" value="135" oninput="grUp()" style="width:120px" /><span id="gr-av" style="font-size:var(--text-xs)">135°</span></div><div><label>C1</label><input type="color" id="gr-c1" value="#6366f1" oninput="grUp()" /></div><div><label>C2</label><input type="color" id="gr-c2" value="#ec4899" oninput="grUp()" /></div><div><label>C3</label><input type="color" id="gr-c3" value="#f59e0b" oninput="grUp()" /></div></div><div id="gr-prev" style="height:160px;border-radius:var(--r-md);margin-bottom:var(--sp-4);border:1px solid var(--border)"></div><div class="output" id="gr-out" style="min-height:auto">Loading…</div></div>`,init:()=>{grUp();}};
window.grUp=()=>{const t=$('gr-type').value,a=$('gr-ang').value,c1=$('gr-c1').value,c2=$('gr-c2').value,c3=$('gr-c3').value;$('gr-av').textContent=a+'°';let css;if(t==='linear')css=`background: linear-gradient(${a}deg, ${c1}, ${c2}, ${c3});`;else if(t==='radial')css=`background: radial-gradient(circle, ${c1}, ${c2}, ${c3});`;else css=`background: conic-gradient(from ${a}deg, ${c1}, ${c2}, ${c3});`;$('gr-prev').style.background=css.replace('background: ','').replace(';','');$('gr-out').textContent=css;};

// ─── Border Radius ───
const borderRadius={name:'Border Radius',icon:'⬜',render:()=>`<div class="panel"><h2>CSS Border Radius</h2><p class="desc">Generate border-radius values with live preview.</p><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:var(--sp-3);margin-bottom:var(--sp-4)"><div><label>Top Left</label><input type="range" id="br-tl" min="0" max="100" value="12" oninput="brUp()" /><span id="br-tlv">12px</span></div><div><label>Top Right</label><input type="range" id="br-tr" min="0" max="100" value="12" oninput="brUp()" /><span id="br-trv">12px</span></div><div><label>Bottom Right</label><input type="range" id="br-br" min="0" max="100" value="12" oninput="brUp()" /><span id="br-brv">12px</span></div><div><label>Bottom Left</label><input type="range" id="br-bl" min="0" max="100" value="12" oninput="brUp()" /><span id="br-blv">12px</span></div></div><div style="display:flex;align-items:center;justify-content:center;padding:var(--sp-10);background:var(--surface-sunken);border-radius:var(--r-md);margin-bottom:var(--sp-4)"><div id="br-box" style="width:160px;height:100px;background:var(--accent);opacity:0.8"></div></div><div class="output" id="br-out" style="min-height:auto">Loading…</div></div>`,init:()=>{brUp();}};
window.brUp=()=>{const tl=$('br-tl').value,tr=$('br-tr').value,br2=$('br-br').value,bl=$('br-bl').value;['tl','tr','br','bl'].forEach(c=>$('br-'+c+'v').textContent=$('br-'+c).value+'px');const css=`border-radius: ${tl}px ${tr}px ${br2}px ${bl}px;`;$('br-box').style.borderRadius=`${tl}px ${tr}px ${br2}px ${bl}px`;$('br-out').textContent=css;};

// ─── Text Shadow ───
const textShadow={name:'Text Shadow',icon:'🔤',render:()=>`<div class="panel"><h2>CSS Text Shadow</h2><p class="desc">Generate text-shadow effects with live preview.</p><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;align-items:end;margin-bottom:var(--sp-4)"><div><label>X</label><input type="range" id="ts-x" min="-20" max="20" value="1" oninput="tsUp()" /><span id="ts-xv">1px</span></div><div><label>Y</label><input type="range" id="ts-y" min="-20" max="20" value="1" oninput="tsUp()" /><span id="ts-yv">1px</span></div><div><label>Blur</label><input type="range" id="ts-bl" min="0" max="30" value="2" oninput="tsUp()" /><span id="ts-bv">2px</span></div><div><label>Color</label><input type="color" id="ts-c" value="#000000" oninput="tsUp()" /></div></div><div id="ts-prev" style="font-size:var(--text-3xl);font-weight:700;text-align:center;padding:var(--sp-8);background:var(--surface-sunken);border-radius:var(--r-md);margin-bottom:var(--sp-4)">Hello World</div><div class="output" id="ts-out" style="min-height:auto">Loading…</div></div>`,init:()=>{tsUp();}};
window.tsUp=()=>{const x=$('ts-x').value,y=$('ts-y').value,bl=$('ts-bl').value,c=$('ts-c').value;$('ts-xv').textContent=x+'px';$('ts-yv').textContent=y+'px';$('ts-bv').textContent=bl+'px';const css=`text-shadow: ${x}px ${y}px ${bl}px ${c};`;$('ts-prev').style.textShadow=`${x}px ${y}px ${bl}px ${c}`;$('ts-out').textContent=css;};

// ─── Circle Generator (inspired by donatj/Circle-Generator) ───
const circleGen={name:'Pixel Circle Generator',icon:'⭕',render:()=>`<div class="panel"><h2>Pixel Circle Generator</h2><p class="desc">Generate pixel circles and ovals for block building games like Minecraft. Based on <a href="https://github.com/donatj/Circle-Generator" target="_blank">donatj/Circle-Generator</a>.</p><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;align-items:end;margin-bottom:var(--sp-4)"><div><label>Width</label><input type="number" id="cg-w" value="16" min="3" max="128" style="width:80px" oninput="cgUp()" /></div><div><label>Height</label><input type="number" id="cg-h" value="16" min="3" max="128" style="width:80px" oninput="cgUp()" /></div><div><label>Thickness</label><input type="number" id="cg-t" value="1" min="1" max="10" style="width:80px" oninput="cgUp()" /></div><div><label>Style</label><select id="cg-style" onchange="cgUp()"><option value="filled">Filled</option><option value="outline">Outline</option></select></div><div><label>Shape</label><select id="cg-shape" onchange="cgUp()"><option value="circle">Circle</option><option value="oval">Oval</option></select></div></div><div id="cg-canvas" style="background:var(--surface-sunken);border:1px solid var(--border);border-radius:var(--r-md);padding:var(--sp-4);margin-bottom:var(--sp-4);overflow:auto;text-align:center"></div><div class="output" id="cg-out" style="min-height:auto">Pixel data will appear here…</div></div>`,init:()=>{cgUp();}};
window.cgUp=()=>{const w=parseInt($('cg-w').value)||16,h=parseInt($('cg-h').value)||16,th=parseInt($('cg-t').value)||1,style=$('cg-style').value,shape=$('cg-shape').value;
  const cells=[];let total=0;
  for(let y=0;y<h;y++){const row=[];for(let x=0;x<w;x++){const nx=(x+0.5)/w*2-1,ny=(y+0.5)/h*2-1;const d=nx*nx+ny*ny;let inside=shape==='circle'?d<=1:(nx*nx+ny*ny<=1);if(style==='outline'&&inside){const outerD=(nx+2/w)*(nx+2/w)+(ny+2/h)*(ny+2/h);inside=d<=1&&outerD>1-(th*Math.max(2/w,2/h));}row.push(inside?1:0);if(inside)total++;}cells.push(row);}
  let html=`<div style="display:inline-block;background:#1e293b;padding:4px;border-radius:4px;line-height:1">`;
  for(const row of cells){html+=`<div style="display:flex">`;for(const c of row){html+=`<div style="width:12px;height:12px;background:${c?'#22c55e':'#334155'};border:1px solid ${c?'#16a34a':'#1e293b'}"></div>`;}html+=`</div>`;}html+=`</div>`;
  $('cg-canvas').innerHTML=html;
  $('cg-out').textContent=`Circle: ${w}×${h} pixels\nFilled blocks: ${total}\nTotal blocks: ${w*h}\nStyle: ${style} | Shape: ${shape}`;};

// ─── QR Code Generator (using qrcode.js CDN) ───
const qrGen={name:'QR Code Generator',icon:'📱',render:()=>`<div class="panel"><h2>QR Code Generator</h2><p class="desc">Generate QR codes from text or URLs. Based on <a href="https://github.com/nayuki/QR-Code-generator" target="_blank">nayuki/QR-Code-generator</a>.</p><label>Text or URL</label><textarea id="qr-in" placeholder="https://example.com" style="min-height:80px" oninput="qrUp()"></textarea><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;align-items:end;margin-top:var(--sp-3)"><div><label>Size</label><select id="qr-size" onchange="qrUp()"><option value="4">Small</option><option value="6" selected>Medium</option><option value="8">Large</option></select></div><div><label>Color</label><input type="color" id="qr-color" value="#000000" oninput="qrUp()" /></div><div><label>Background</label><input type="color" id="qr-bg" value="#ffffff" oninput="qrUp()" /></div></div><div id="qr-preview" style="margin-top:var(--sp-4);text-align:center"></div><div class="btn-group"><button class="btn btn-secondary" onclick="qrDownload()">Download PNG</button></div></div>`,init:()=>{if(!window.QRCode){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcode@1.5.3/build/qrcode.min.js';document.head.appendChild(s);s.onload=()=>qrUp();}else qrUp();}};
window.qrUp=()=>{const text=$('qr-in').value;if(!text||!window.QRCode){$('qr-preview').innerHTML='<p style="color:var(--ink-4)">Enter text to generate QR code…</p>';return;}const sz=parseInt($('qr-size').value)*100;const c=$('qr-color').value;const bg=$('qr-bg').value;try{const canvas=document.createElement('canvas');QRCode.toCanvas(canvas,text,{width:sz,margin:2,color:{dark:c,light:bg}},err=>{if(err){$('qr-preview').textContent='❌ '+err.message;return;}canvas.id='qr-canvas';canvas.style.borderRadius='var(--r-md)';canvas.style.border='1px solid var(--border)';$('qr-preview').innerHTML='';$('qr-preview').appendChild(canvas);});}catch(e){$('qr-preview').textContent='❌ '+e.message;}};
window.qrDownload=()=>{const c=document.getElementById('qr-canvas');if(!c)return;const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='qr-code.png';a.click();};

// ─── CSS Button Generator ───
const btnGen={name:'CSS Button Generator',icon:'🔘',render:()=>`<div class="panel"><h2>CSS Button Generator</h2><p class="desc">Generate custom CSS buttons with live preview.</p><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:var(--sp-3);margin-bottom:var(--sp-4)"><div><label>Background</label><input type="color" id="bg-bg" value="#2563eb" oninput="bgUp()" /></div><div><label>Text Color</label><input type="color" id="bg-tc" value="#ffffff" oninput="bgUp()" /></div><div><label>Border Radius</label><input type="range" id="bg-r" min="0" max="50" value="8" oninput="bgUp()" /><span id="bg-rv">8px</span></div><div><label>Padding X</label><input type="range" id="bg-px" min="4" max="40" value="16" oninput="bgUp()" /><span id="bg-pxv">16px</span></div><div><label>Padding Y</label><input type="range" id="bg-py" min="4" max="30" value="10" oninput="bgUp()" /><span id="bg-pyv">10px</span></div><div><label>Font Size</label><input type="range" id="bg-fs" min="10" max="24" value="14" oninput="bgUp()" /><span id="bg-fsv">14px</span></div><div><label>Border Width</label><input type="range" id="bg-bw" min="0" max="4" value="0" oninput="bgUp()" /><span id="bg-bwv">0px</span></div><div><label>Border Color</label><input type="color" id="bg-bc" value="#1d4ed8" oninput="bgUp()" /></div></div><div style="display:flex;align-items:center;justify-content:center;padding:var(--sp-10);background:var(--surface-sunken);border-radius:var(--r-md);margin-bottom:var(--sp-4)"><button id="bg-btn" style="cursor:default">Button Text</button></div><div class="output" id="bg-out" style="min-height:auto">Loading…</div></div>`,init:()=>{bgUp();}};
window.bgUp=()=>{const bg=$('bg-bg').value,tc=$('bg-tc').value,r=$('bg-r').value,px=$('bg-px').value,py=$('bg-py').value,fs=$('bg-fs').value,bw=$('bg-bw').value,bc=$('bg-bc').value;$('bg-rv').textContent=r+'px';$('bg-pxv').textContent=px+'px';$('bg-pyv').textContent=py+'px';$('bg-fsv').textContent=fs+'px';$('bg-bwv').textContent=bw+'px';const btn=$('bg-btn');btn.style.cssText=`background:${bg};color:${tc};border-radius:${r}px;padding:${py}px ${px}px;font-size:${fs}px;border:${bw}px solid ${bc};cursor:default;font-weight:600;transition:opacity .15s;font-family:inherit;`;$('bg-out').textContent=`background: ${bg};\ncolor: ${tc};\nborder-radius: ${r}px;\npadding: ${py}px ${px}px;\nfont-size: ${fs}px;\nborder: ${bw}px solid ${bc};\nfont-weight: 600;\ntransition: opacity 0.15s;`;};

// ─── Placeholder Images ───
const loremImg={name:'Placeholder Images',icon:'🖼️',render:()=>`<div class="panel"><h2>Placeholder Image Generator</h2><p class="desc">Generate colored placeholder images with custom text.</p><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;align-items:end;margin-bottom:var(--sp-4)"><div><label>Width</label><input type="number" id="pi-w" value="400" style="width:90px" /></div><div><label>Height</label><input type="number" id="pi-h" value="300" style="width:90px" /></div><div><label>BG</label><input type="color" id="pi-bg" value="#e2e8f0" /></div><div><label>Text</label><input type="color" id="pi-tc" value="#64748b" /></div><div><label>Label</label><input type="text" id="pi-txt" value="400 × 300" style="width:120px" /></div><button class="btn btn-primary" onclick="piGen()">Generate</button></div><div id="pi-preview" style="margin-bottom:var(--sp-4);border-radius:var(--r-md);overflow:hidden;border:1px solid var(--border);display:inline-block"></div></div>`,init:()=>{}};
window.piGen=()=>{const w=parseInt($('pi-w').value)||400,h=parseInt($('pi-h').value)||300,bg=$('pi-bg').value,tc=$('pi-tc').value,txt=$('pi-txt').value||`${w}×${h}`;const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=tc;ctx.font=`${Math.min(w,h)/6}px DM Sans, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(txt,w/2,h/2);$('pi-preview').innerHTML='';$('pi-preview').appendChild(c);};

export const DesignTools={tools:{'color-contrast':colorPicker,'box-shadow':boxShadow,'css-gradient':cssGradient,'border-radius':borderRadius,'text-shadow':textShadow,'circle-generator':circleGen,'qr-code-generator':qrGen,'css-button-generator':btnGen,'placeholder-images':loremImg,}};
