// ============================================================
// Developer Tools — 14 tools
// ============================================================
function $(id){return document.getElementById(id);}

const jsonFmt={name:'JSON Formatter',icon:'📝',render:()=>`<div class="panel"><h2>JSON Formatter & Validator</h2><p class="desc">Format, validate, minify, or convert JSON to CSV/tree view.</p><label>Input JSON</label><textarea id="jf-in" placeholder='{"name":"WebTools","items":[1,2,3]}'></textarea><div class="btn-group"><button class="btn btn-primary" onclick="jfFmt()">Format</button><button class="btn btn-secondary" onclick="jfMin()">Minify</button><button class="btn btn-secondary" onclick="jfCsv()">To CSV</button><button class="btn btn-secondary" onclick="jfTree()">Tree View</button></div><label style="margin-top:var(--sp-4)">Output</label><div class="output" id="jf-out">Output appears here…</div></div>`,init:()=>{}};
window.jfFmt=()=>{try{$('jf-out').textContent=JSON.stringify(JSON.parse($('jf-in').value),null,2);}catch(e){$('jf-out').textContent='❌ '+e.message;}};
window.jfMin=()=>{try{$('jf-out').textContent=JSON.stringify(JSON.parse($('jf-in').value));}catch(e){$('jf-out').textContent='❌ '+e.message;}};
window.jfCsv=()=>{try{const d=JSON.parse($('jf-in').value);const a=Array.isArray(d)?d:[d];if(!a.length){$('jf-out').textContent='Empty';return;}const h=Object.keys(a[0]);$('jf-out').textContent=h.join(',')+'\n'+a.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(',')).join('\n');}catch(e){$('jf-out').textContent='❌ '+e.message;}};
window.jfTree=()=>{try{const d=JSON.parse($('jf-in').value);function t(o,p='',l=true){if(o===null)return'null';if(typeof o!=='object')return String(o);const ia=Array.isArray(o);const e=ia?o.map((v,i)=>[i,v]):Object.entries(o);let out=ia?'[\n':'{\n';e.forEach(([k,v],i)=>{const last=i===e.length-1;const c=last?'└── ':'├── ';const ch=typeof v==='object'&&v!==null?t(v,p+(last?'    ':'│   '),last):String(v);out+=p+c+(ia?'':k+': ')+ch+'\n';});out+=p+(ia?']':'}');return out;}$('jf-out').textContent=t(d);}catch(e){$('jf-out').textContent='❌ '+e.message;}};

const uuidGen={name:'UUID Generator',icon:'🔑',render:()=>`<div class="panel"><h2>UUID Generator</h2><p class="desc">Generate UUID v4 identifiers. Click any line to copy.</p><div style="display:flex;gap:var(--sp-3);align-items:end;flex-wrap:wrap;margin-bottom:var(--sp-4)"><div><label>Count</label><input type="number" id="uuid-n" value="5" min="1" max="500" style="width:90px" /></div><button class="btn btn-primary" onclick="uuidGo()">Generate</button><button class="btn btn-secondary" onclick="navigator.clipboard.writeText($('uuid-out').textContent)">Copy All</button></div><div class="output" id="uuid-out">Click Generate…</div></div>`,init:()=>{}};
window.uuidGo=()=>{const n=Math.min(parseInt($('uuid-n').value)||5,500);$('uuid-out').innerHTML=Array.from({length:n},()=>crypto.randomUUID()).map(l=>`<div style="padding:3px 0;border-bottom:1px solid var(--border);cursor:pointer" onclick="navigator.clipboard.writeText('${l}');this.style.background='var(--green-soft)';setTimeout(()=>this.style.background='',400)">${l}</div>`).join('');};

const base64={name:'Base64 Encoder/Decoder',icon:'🔄',render:()=>`<div class="panel"><h2>Base64 Encoder / Decoder</h2><p class="desc">Encode text to Base64 or decode Base64. Supports Unicode.</p><label>Input</label><textarea id="b64-in" placeholder="Enter text or Base64…"></textarea><div class="btn-group"><button class="btn btn-primary" onclick="b64Enc()">Encode →</button><button class="btn btn-primary" onclick="b64Dec()">← Decode</button></div><label style="margin-top:var(--sp-4)">Output</label><div class="output" id="b64-out">Output appears here…</div></div>`,init:()=>{}};
window.b64Enc=()=>{try{$('b64-out').textContent=btoa(unescape(encodeURIComponent($('b64-in').value)));}catch(e){$('b64-out').textContent='❌ '+e.message;}};
window.b64Dec=()=>{try{$('b64-out').textContent=decodeURIComponent(escape(atob($('b64-in').value.trim())));}catch(e){$('b64-out').textContent='❌ Invalid Base64';}};

const hashGen={name:'Hash Generator',icon:'#️⃣',render:()=>`<div class="panel"><h2>Hash Generator</h2><p class="desc">SHA-256 and SHA-1 hashes (Web Crypto API).</p><label>Input Text</label><textarea id="hash-in" placeholder="Enter text to hash…"></textarea><div class="btn-group"><button class="btn btn-primary" onclick="hashGo()">Generate</button></div><label style="margin-top:var(--sp-4)">Output</label><div class="output" id="hash-out">Click Generate…</div></div>`,init:()=>{}};
window.hashGo=async()=>{const t=$('hash-in').value;if(!t)return;const d=new TextEncoder().encode(t);let o='';for(const a of['SHA-256','SHA-1']){const b=await crypto.subtle.digest(a,d);o+=`${a}:\n${Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}\n\n`;}$('hash-out').textContent=o;};

const regexTool={name:'Regex Tester',icon:'🔍',render:()=>`<div class="panel"><h2>Regex Tester</h2><p class="desc">Test regular expressions with real-time matching.</p><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;margin-bottom:var(--sp-3)"><div style="flex:1;min-width:200px"><label>Pattern</label><input type="text" id="rx-pat" placeholder="[a-z]+@[a-z]+\\.[a-z]+" oninput="rxTest()" /></div><div style="width:100px"><label>Flags</label><input type="text" id="rx-flags" value="gi" oninput="rxTest()" /></div></div><label>Test String</label><textarea id="rx-in" placeholder="Enter test text…" oninput="rxTest()"></textarea><label style="margin-top:var(--sp-4)">Matches</label><div class="output" id="rx-out">Type pattern and text…</div></div>`,init:()=>{}};
window.rxTest=()=>{const p=$('rx-pat').value,f=$('rx-flags').value,i=$('rx-in').value;if(!p||!i){$('rx-out').textContent='Type pattern and text…';return;}try{const re=new RegExp(p,f),ms=[];let m;if(f.includes('g')){while((m=re.exec(i))!==null){ms.push(m);if(m.index===re.lastIndex)re.lastIndex++;}}else{m=re.exec(i);if(m)ms.push(m);}if(!ms.length){$('rx-out').textContent='No matches.';return;}$('rx-out').textContent=`Found ${ms.length} match(es):\n\n`+ms.map((m,i)=>`Match ${i+1}: "${m[0]}" at index ${m.index}${m.length>1?'\n  Groups: '+m.slice(1).map((g,j)=>`$${j+1}="${g}"`).join(', '):''}`).join('\n\n');}catch(e){$('rx-out').textContent='❌ '+e.message;}};

const pwGen={name:'Password Generator',icon:'🔐',render:()=>`<div class="panel"><h2>Password Generator</h2><p class="desc">Cryptographically secure random passwords.</p><div style="display:flex;gap:var(--sp-4);flex-wrap:wrap;align-items:end;margin-bottom:var(--sp-4)"><div><label>Length</label><input type="number" id="pw-len" value="20" min="4" max="200" style="width:80px" /></div><label style="margin:0;display:flex;align-items:center;gap:4px"><input type="checkbox" id="pw-up" checked> ABC</label><label style="margin:0;display:flex;align-items:center;gap:4px"><input type="checkbox" id="pw-lo" checked> abc</label><label style="margin:0;display:flex;align-items:center;gap:4px"><input type="checkbox" id="pw-num" checked> 123</label><label style="margin:0;display:flex;align-items:center;gap:4px"><input type="checkbox" id="pw-sym" checked> !@#</label></div><div class="btn-group"><button class="btn btn-primary" onclick="pwGo()">Generate</button><button class="btn btn-secondary" onclick="navigator.clipboard.writeText($('pw-out').textContent)">Copy</button></div><label style="margin-top:var(--sp-4)">Password</label><div class="output" id="pw-out" style="font-size:1.05rem;letter-spacing:1px">Click Generate…</div></div>`,init:()=>{}};
window.pwGo=()=>{const l=parseInt($('pw-len').value)||20;let c='';if($('pw-up').checked)c+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if($('pw-lo').checked)c+='abcdefghijklmnopqrstuvwxyz';if($('pw-num').checked)c+='0123456789';if($('pw-sym').checked)c+='!@#$%^&*()_+-=[]{}|;:,.<>?';if(!c)c='abcdefghijklmnopqrstuvwxyz';const a=new Uint32Array(l);crypto.getRandomValues(a);$('pw-out').textContent=Array.from(a,x=>c[x%c.length]).join('');};

const cidrCalc={name:'CIDR Calculator',icon:'🌐',render:()=>`<div class="panel"><h2>CIDR / Subnet Calculator</h2><p class="desc">Calculate network range, broadcast, and hosts.</p><label>CIDR Notation</label><input type="text" id="cidr-in" placeholder="192.168.1.0/24" /><div class="btn-group"><button class="btn btn-primary" onclick="cidrGo()">Calculate</button></div><label style="margin-top:var(--sp-4)">Result</label><div class="output" id="cidr-out">Enter CIDR…</div></div>`,init:()=>{}};
window.cidrGo=()=>{const i=$('cidr-in').value.trim(),m=i.match(/^(\d+\.\d+\.\d+\.\d+)\/(\d+)$/);if(!m){$('cidr-out').textContent='❌ Use: x.x.x.x/n';return;}const ip=m[1].split('.').map(Number),c=parseInt(m[2]);if(ip.some(o=>o<0||o>255)||c<0||c>32){$('cidr-out').textContent='❌ Invalid';return;}const mask=c===0?0:(~0<<(32-c))>>>0;const n=(ip[0]<<24|ip[1]<<16|ip[2]<<8|ip[3])>>>0;const net=(n&mask)>>>0;const b=(net|~mask)>>>0;const h=c>=31?(c===32?1:2):b-net-1;const td=x=>[(x>>>24)&255,(x>>>16)&255,(x>>>8)&255,x&255].join('.');$('cidr-out').textContent=`Network:    ${td(net)}/${c}\nMask:       ${td(mask)}\nBroadcast:  ${td(b)}\nHost Range: ${td(net+1)} — ${td(b-1)}\nHosts:      ${h.toLocaleString()}`;};

const tsConv={name:'Timestamp Converter',icon:'⏰',render:()=>`<div class="panel"><h2>Unix Timestamp Converter</h2><p class="desc">Convert between Unix timestamps and dates.</p><div style="display:flex;gap:var(--sp-3);flex-wrap:wrap;margin-bottom:var(--sp-4)"><div style="flex:1;min-width:200px"><label>Unix Timestamp</label><input type="text" id="ts-in" oninput="tsToDate()" /></div><div style="flex:1;min-width:200px"><label>Date/Time</label><input type="datetime-local" id="ts-date" step="1" oninput="dateToTs()" /></div></div><div class="output" id="ts-out">Enter timestamp or date…</div></div>`,init:()=>{$('ts-date').value=new Date().toISOString().slice(0,19);$('ts-in').value=Math.floor(Date.now()/1000);}};
window.tsToDate=()=>{const ts=parseInt($('ts-in').value.trim());if(isNaN(ts)){$('ts-out').textContent='Invalid';return;}const d=new Date(ts>1e11?ts:ts*1000);$('ts-out').textContent=`Human:  ${d.toLocaleString()}\nISO:    ${d.toISOString()}\nUTC:    ${d.toUTCString()}\nMS:     ${d.getTime()}`;};
window.dateToTs=()=>{const d=new Date($('ts-date').value);if(isNaN(d))return;$('ts-in').value=Math.floor(d.getTime()/1000);tsToDate();};

const jwtDec={name:'JWT Decoder',icon:'🎫',render:()=>`<div class="panel"><h2>JWT Decoder</h2><p class="desc">Decode JSON Web Tokens to view header and payload.</p><label>JWT Token</label><textarea id="jwt-in" placeholder="eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.xxx" style="min-height:80px"></textarea><div class="btn-group"><button class="btn btn-primary" onclick="jwtDecode()">Decode</button></div><label style="margin-top:var(--sp-4)">Output</label><div class="output" id="jwt-out">Paste JWT…</div></div>`,init:()=>{}};
window.jwtDecode=()=>{try{const p=$('jwt-in').value.trim().split('.');if(p.length<2){$('jwt-out').textContent='❌ Invalid JWT';return;}const h=JSON.parse(atob(p[0].replace(/-/g,'+').replace(/_/g,'/')));const pl=JSON.parse(atob(p[1].replace(/-/g,'+').replace(/_/g,'/')));let o=`HEADER:\n${JSON.stringify(h,null,2)}\n\nPAYLOAD:\n${JSON.stringify(pl,null,2)}`;if(pl.exp)o+=`\n\nExpires: ${new Date(pl.exp*1000).toLocaleString()}`;if(pl.iat)o+=`\nIssued:  ${new Date(pl.iat*1000).toLocaleString()}`;$('jwt-out').textContent=o;}catch(e){$('jwt-out').textContent='❌ '+e.message;}};

const cronGen={name:'Cron Expression Generator',icon:'⏱️',render:()=>`<div class="panel"><h2>Cron Expression Generator</h2><p class="desc">Build cron expressions with live human-readable descriptions.</p><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:var(--sp-3);margin-bottom:var(--sp-4)"><div><label>Min (0-59)</label><input type="text" id="cr-min" value="*" oninput="cronBuild()" /></div><div><label>Hour (0-23)</label><input type="text" id="cr-hour" value="*" oninput="cronBuild()" /></div><div><label>Day (1-31)</label><input type="text" id="cr-day" value="*" oninput="cronBuild()" /></div><div><label>Month (1-12)</label><input type="text" id="cr-mon" value="*" oninput="cronBuild()" /></div><div><label>Weekday (0-6)</label><input type="text" id="cr-wk" value="*" oninput="cronBuild()" /></div></div><div style="display:flex;gap:var(--sp-2);flex-wrap:wrap;margin-bottom:var(--sp-4)"><button class="btn btn-sm btn-secondary" onclick="cronP('0 * * * *')">Every hour</button><button class="btn btn-sm btn-secondary" onclick="cronP('0 0 * * *')">Daily midnight</button><button class="btn btn-sm btn-secondary" onclick="cronP('0 0 * * 0')">Weekly Sunday</button><button class="btn btn-sm btn-secondary" onclick="cronP('*/5 * * * *')">Every 5 min</button></div><div class="output" id="cron-out">Adjust fields…</div></div>`,init:()=>{cronBuild();}};
window.cronP=e=>{const p=e.split(' ');$('cr-min').value=p[0];$('cr-hour').value=p[1];$('cr-day').value=p[2];$('cr-mon').value=p[3];$('cr-wk').value=p[4];cronBuild();};
window.cronBuild=()=>{const m=$('cr-min').value,h=$('cr-hour').value,d=$('cr-day').value,mo=$('cr-mon').value,w=$('cr-wk').value;const expr=`${m} ${h} ${d} ${mo} ${w}`;let desc=`Expression: ${expr}\n\n`;desc+=m==='*'?'Every minute':m.startsWith('*/')?`Every ${m.slice(2)} min`:`At min ${m}`;desc+=h==='*'?' of every hour':h.startsWith('*/')?` every ${h.slice(2)}h`:` at hour ${h}`;desc+=d==='*'?'':` on day ${d}`;desc+=mo==='*'?'':` month ${mo}`;const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];desc+=w==='*'?'':` on ${days[parseInt(w)]||w}`;$('cron-out').textContent=desc;};

const urlEnc={name:'URL Encoder/Decoder',icon:'🔗',render:()=>`<div class="panel"><h2>URL Encoder / Decoder</h2><p class="desc">Encode or decode URL strings.</p><label>Input</label><textarea id="url-in" placeholder="https://example.com/path?q=hello world" style="min-height:60px"></textarea><div class="btn-group"><button class="btn btn-primary" onclick="urlEncode()">Encode →</button><button class="btn btn-primary" onclick="urlDecode()">← Decode</button><button class="btn btn-secondary" onclick="urlEncComp()">Encode URI →</button></div><label style="margin-top:var(--sp-4)">Output</label><div class="output" id="url-out">Output appears here…</div></div>`,init:()=>{}};
window.urlEncode=()=>{$('url-out').textContent=encodeURIComponent($('url-in').value);};
window.urlDecode=()=>{try{$('url-out').textContent=decodeURIComponent($('url-in').value);}catch(e){$('url-out').textContent='❌ '+e.message;}};
window.urlEncComp=()=>{$('url-out').textContent=encodeURI($('url-in').value);};

const htmlEnt={name:'HTML Entities',icon:'🏷️',render:()=>`<div class="panel"><h2>HTML Entity Encoder / Decoder</h2><p class="desc">Encode special characters to HTML entities or decode them.</p><label>Input</label><textarea id="html-in" placeholder="<div class='test'>Hello & World</div>" style="min-height:60px"></textarea><div class="btn-group"><button class="btn btn-primary" onclick="htmlEncode()">Encode →</button><button class="btn btn-primary" onclick="htmlDecode()">← Decode</button></div><label style="margin-top:var(--sp-4)">Output</label><div class="output" id="html-out">Output appears here…</div></div>`,init:()=>{}};
window.htmlEncode=()=>{const s=$('html-in').value;$('html-out').textContent=s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');};
window.htmlDecode=()=>{const d=document.createElement('div');d.innerHTML=$('html-in').value;$('html-out').textContent=d.textContent;};

const baseConv={name:'Base Converter',icon:'🔢',render:()=>`<div class="panel"><h2>Number Base Converter</h2><p class="desc">Convert between Binary, Octal, Decimal, and Hex.</p><label>Decimal Input</label><input type="text" id="base-in" placeholder="42" oninput="baseConvGo()" /><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:var(--sp-3);margin-top:var(--sp-4)"><div><label>Binary</label><div class="output" id="base-bin" style="min-height:auto;padding:var(--sp-3)">—</div></div><div><label>Octal</label><div class="output" id="base-oct" style="min-height:auto;padding:var(--sp-3)">—</div></div><div><label>Hex</label><div class="output" id="base-hex" style="min-height:auto;padding:var(--sp-3)">—</div></div></div></div>`,init:()=>{}};
window.baseConvGo=()=>{const v=parseInt($('base-in').value);if(isNaN(v)){$('base-bin').textContent=$('base-oct').textContent=$('base-hex').textContent='—';return;}$('base-bin').textContent=v.toString(2);$('base-oct').textContent=v.toString(8);$('base-hex').textContent=v.toString(16).toUpperCase();};

const colorConv={name:'Color Converter',icon:'🎨',render:()=>`<div class="panel"><h2>Color Converter</h2><p class="desc">Convert between HEX, RGB, and HSL color formats.</p><div style="display:flex;gap:var(--sp-3);align-items:end;flex-wrap:wrap;margin-bottom:var(--sp-4)"><div style="flex:1;min-width:120px"><label>HEX</label><input type="text" id="col-hex" placeholder="#6366f1" oninput="colFromHex()" /></div><div><label>RGB</label><input type="text" id="col-rgb" placeholder="99, 102, 241" oninput="colFromRgb()" style="width:160px" /></div><div style="width:60px;height:42px;border-radius:var(--r-sm);border:1px solid var(--border);overflow:hidden"><input type="color" id="col-pick" value="#6366f1" style="width:100%;height:100%;border:none;cursor:pointer" oninput="colFromPicker()" /></div></div><div class="output" id="col-out" style="min-height:auto">Enter a color…</div></div>`,init:()=>{}};
function hexToRgb(h){h=h.replace('#','');if(h.length===3)h=h[0]+h[0]+h[1]+h[1]+h[2]+h[2];return{r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)};}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),l=(mx+mn)/2;let h,s;if(mx===mn){h=s=0;}else{const d=mx-mn;s=l>.5?d/(2-mx-mn):d/(mx+mn);switch(mx){case r:h=((g-b)/d+(g<b?6:0))/6;break;case g:h=((b-r)/d+2)/6;break;case b:h=((r-g)/d+4)/6;break;}}return{h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)};}
function rgbToHex(r,g,b){return '#'+[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join('');}
window.colFromHex=()=>{const h=$('col-hex').value;if(!h.match(/^#?[0-9a-f]{3,6}$/i))return;const rgb=hexToRgb(h);const hsl=rgbToHsl(rgb.r,rgb.g,rgb.b);$('col-rgb').value=`${rgb.r}, ${rgb.g}, ${rgb.b}`;$('col-pick').value=rgbToHex(rgb.r,rgb.g,rgb.b);$('col-out').textContent=`HEX: ${rgbToHex(rgb.r,rgb.g,rgb.b)}\nRGB: rgb(${rgb.r}, ${rgb.g}, ${rgb.b})\nHSL: hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`;};
window.colFromRgb=()=>{const m=$('col-rgb').value.match(/(\d+),\s*(\d+),\s*(\d+)/);if(!m)return;const[r,g,b]=m.slice(1).map(Number);const hex=rgbToHex(r,g,b);const hsl=rgbToHsl(r,g,b);$('col-hex').value=hex;$('col-pick').value=hex;$('col-out').textContent=`HEX: ${hex}\nRGB: rgb(${r}, ${g}, ${b})\nHSL: hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`;};
window.colFromPicker=()=>{const h=$('col-pick').value;$('col-hex').value=h;colFromHex();};

export const DevTools={tools:{'json-formatter':jsonFmt,'uuid-generator':uuidGen,'base64':base64,'hash-generator':hashGen,'regex-tester':regexTool,'password-generator':pwGen,'cidr-calculator':cidrCalc,'timestamp-converter':tsConv,'jwt-decoder':jwtDec,'cron-generator':cronGen,'url-encoder':urlEnc,'html-entities':htmlEnt,'base-converter':baseConv,'color-converter':colorConv,}};
