// ============================================================
// PDF Tools — 3 tools (pdf-lib from CDN)
// ============================================================
function $(id){return document.getElementById(id);}
let pdfLibReady=false;
async function ensurePdfLib(){if(pdfLibReady)return window.PDFLib;return new Promise((r,j)=>{const s=document.createElement('script');s.src='https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js';s.onload=()=>{pdfLibReady=true;r(window.PDFLib);};s.onerror=()=>j(new Error('Failed to load pdf-lib'));document.head.appendChild(s);});}
function setupDrop(id,cb){const el=document.getElementById(id);if(!el)return;el.addEventListener('dragover',e=>{e.preventDefault();el.classList.add('dragover');});el.addEventListener('dragleave',()=>el.classList.remove('dragover'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('dragover');cb(e.dataTransfer.files);});}
function fmtBytes(b){return b<1024?b+' B':(b/1024).toFixed(1)+' KB';}
function dlBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);}

let mergeFiles=[];
const mergePdf={name:'Merge PDFs',icon:'📎',render:()=>`<div class="panel"><h2>Merge PDF Files</h2><p class="desc">Combine multiple PDFs into one. Drag to reorder.</p><div class="dropzone" id="m-drop"><div class="dropzone-icon">📄</div><div>Click or drag PDF files here</div></div><input type="file" id="m-input" accept=".pdf" multiple style="display:none" /><div class="file-list" id="m-files"></div><div class="btn-group"><button class="btn btn-primary" onclick="mMerge()">🔗 Merge</button><button class="btn btn-secondary" onclick="mClear()">Clear</button></div><div id="m-status" style="margin-top:var(--sp-3);font-size:var(--text-sm);color:var(--ink-3)"></div></div>`,init:()=>{mergeFiles=[];$('m-input').addEventListener('change',e=>{mAdd(e.target.files);e.target.value='';});$('m-drop').addEventListener('click',()=>$('m-input').click());setupDrop('m-drop',f=>mAdd(f));}};
window.mAdd=fs=>{for(const f of fs)if(f.type==='application/pdf')mergeFiles.push(f);mList();};
function mList(){$('m-files').innerHTML=mergeFiles.map((f,i)=>`<div class="file-item"><span class="name">${f.name}</span><span class="size">${fmtBytes(f.size)}</span><span class="remove" onclick="mRm(${i})">✕</span></div>`).join('');}
window.mRm=i=>{mergeFiles.splice(i,1);mList();};
window.mClear=()=>{mergeFiles=[];mList();$('m-status').textContent='';};
window.mMerge=async()=>{if(mergeFiles.length<2){$('m-status').textContent='⚠️ Add at least 2 files.';return;}try{$('m-status').textContent='⏳ Merging…';const{PDFDocument}=await ensurePdfLib();const merged=await PDFDocument.create();for(const f of mergeFiles){const b=await f.arrayBuffer();const pdf=await PDFDocument.load(b);const pages=await merged.copyPages(pdf,pdf.getPageIndices());pages.forEach(p=>merged.addPage(p));}const out=await merged.save();dlBlob(new Blob([out],{type:'application/pdf'}),'merged.pdf');$('m-status').textContent=`✅ Merged ${mergeFiles.length} files → merged.pdf`;}catch(e){$('m-status').textContent='❌ '+e.message;}};

let splitData=null,splitPC=0;
const splitPdf={name:'Split PDF',icon:'✂️',render:()=>`<div class="panel"><h2>Split PDF</h2><p class="desc">Extract pages by range: 1-3, 5, 7-10</p><div class="dropzone" id="s-drop"><div class="dropzone-icon">📄</div><div>Click or drag a PDF here</div></div><input type="file" id="s-input" accept=".pdf" style="display:none" /><div id="s-info" style="margin-top:var(--sp-3);font-size:var(--text-sm)"></div><div style="margin-top:var(--sp-4)"><label>Page Range</label><input type="text" id="s-range" placeholder="1-3, 5, 7-10" /></div><div class="btn-group"><button class="btn btn-primary" onclick="sSplit()">✂️ Extract</button></div><div id="s-status" style="margin-top:var(--sp-3);font-size:var(--text-sm);color:var(--ink-3)"></div></div>`,init:()=>{splitData=null;splitPC=0;$('s-input').addEventListener('change',e=>{sLoad(e.target.files[0]);e.target.value='';});$('s-drop').addEventListener('click',()=>$('s-input').click());setupDrop('s-drop',f=>{if(f[0])sLoad(f[0]);});}};
async function sLoad(f){if(!f)return;splitData=await f.arrayBuffer();try{const{PDFDocument}=await ensurePdfLib();const pdf=await PDFDocument.load(splitData);splitPC=pdf.getPageCount();$('s-info').innerHTML=`<strong>${f.name}</strong> — ${splitPC} pages (${fmtBytes(f.size)})`;}catch(e){$('s-info').textContent='❌ Could not read';}}
function parseRange(s,max){const st=new Set();s.split(',').forEach(p=>{p=p.trim();if(p.includes('-')){const[a,b]=p.split('-').map(Number);for(let i=a;i<=Math.min(b,max);i++)st.add(i-1);}else{const n=parseInt(p);if(n>=1&&n<=max)st.add(n-1);}});return[...st].sort((a,b)=>a-b);}
window.sSplit=async()=>{if(!splitData){$('s-status').textContent='⚠️ Load a PDF first.';return;}const r=$('s-range').value.trim();if(!r){$('s-status').textContent='⚠️ Enter a range.';return;}try{$('s-status').textContent='⏳ Extracting…';const{PDFDocument}=await ensurePdfLib();const pdf=await PDFDocument.load(splitData);const pages=parseRange(r,splitPC);if(!pages.length){$('s-status').textContent='⚠️ No valid pages.';return;}const np=await PDFDocument.create();const cp=await np.copyPages(pdf,pages);cp.forEach(p=>np.addPage(p));const out=await np.save();dlBlob(new Blob([out],{type:'application/pdf'}),'split.pdf');$('s-status').textContent=`✅ Extracted ${pages.length} pages`;}catch(e){$('s-status').textContent='❌ '+e.message;}};

let infoData=null;
const pdfInfo={name:'PDF Info & Optimize',icon:'📦',render:()=>`<div class="panel"><h2>PDF Information & Optimize</h2><p class="desc">View metadata and attempt basic optimization.</p><div class="dropzone" id="i-drop"><div class="dropzone-icon">📄</div><div>Click or drag a PDF here</div></div><input type="file" id="i-input" accept=".pdf" style="display:none" /><div class="output" id="i-out" style="min-height:120px">Load a PDF…</div><div class="btn-group"><button class="btn btn-primary" onclick="iOpt()">📦 Optimize & Download</button></div><div id="i-status" style="margin-top:var(--sp-3);font-size:var(--text-sm);color:var(--ink-3)"></div></div>`,init:()=>{infoData=null;$('i-input').addEventListener('change',e=>{iLoad(e.target.files[0]);e.target.value='';});$('i-drop').addEventListener('click',()=>$('i-input').click());setupDrop('i-drop',f=>{if(f[0])iLoad(f[0]);});}};
async function iLoad(f){if(!f)return;infoData=await f.arrayBuffer();try{const{PDFDocument}=await ensurePdfLib();const pdf=await PDFDocument.load(infoData);$('i-out').textContent=`File:     ${f.name}\nSize:     ${fmtBytes(f.size)}\nPages:    ${pdf.getPageCount()}\nTitle:    ${pdf.getTitle()||'N/A'}\nAuthor:   ${pdf.getAuthor()||'N/A'}\nSubject:  ${pdf.getSubject()||'N/A'}\nCreator:  ${pdf.getCreator()||'N/A'}\nProducer: ${pdf.getProducer()||'N/A'}`;}catch(e){$('i-out').textContent='❌ '+e.message;}}
window.iOpt=async()=>{if(!infoData){$('i-status').textContent='⚠️ Load a PDF first.';return;}try{$('i-status').textContent='⏳ Optimizing…';const{PDFDocument}=await ensurePdfLib();const pdf=await PDFDocument.load(infoData,{ignoreEncryption:true});const out=await pdf.save();const orig=infoData.byteLength;dlBlob(new Blob([out],{type:'application/pdf'}),'optimized.pdf');$('i-status').textContent=`✅ ${fmtBytes(orig)} → ${fmtBytes(out.byteLength)}`;}catch(e){$('i-status').textContent='❌ '+e.message;}};

export const PdfTools={tools:{'merge':mergePdf,'split':splitPdf,'info-optimize':pdfInfo,}};
